[package]
name = "troad_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
troad_serde = { version = "0.1.0", path = "../troad_serde" }
uuid = { version = "1.9.1", features = ["serde"] }
