[package]
name = "troad_crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
bnum = "0.11.0"
cfb8 = "0.8.1"
rand = "0.8.5"
rsa = "0.9.6"
sha1_smol = "1.0.0"
tokio = { version = "1.38.0", features = ["net"] }
